name: multi_store_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  cloud_firestore: ^4.8.5
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.7.3
  firebase_core: ^2.15.1
  firebase_storage: ^11.2.6
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  image_picker: ^1.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Brand-Bold
      fonts:
        - asset: assets/fonts/GemunuLibre-Bold.ttf

    - family: Semi-Bold
      fonts:
        - asset: assets/fonts/GemunuLibre-SemiBold.ttf

          weight: 700
